### PR TITLE
feat: add new buildPythonApplication template

### PR DESCRIPTION
**Pull request by limeytexan**
We need templates for `buildPythonApplication` as well as `buildPythonPackage`.

### CODE REVIEW

**Review by mkenigs — CHANGES_REQUESTED** [review]
`package-python-application` currently gets displayed to the user which doesn't seem ideal. Would `package-python` calling `buildPythonApplication` and `module-python` calling `buildPythonPackage` make more sense? Alternatively maybe you'd prefer treewide just using the builder name? I don't remember why we decided to display what we are and don't have super strong opinions, but I do think it should be consistent

**Comment by notgne2** [comment]
@mkenigs @limeytexan

can this be updated or superceded with the requested changes? or is this waiting on someone/something else

**Comment by mkenigs** [comment]
I'm okay with `package-python` calling `buildPythonApplication` and `module-python` calling `buildPythonPackage`. I was waiting for @limeytexan to make that change or suggest something else

**Comment by limeytexan** [comment]
Thanks @mkenigs for highlighting this - I've renamed the templates as you suggest.  👍

**Comment by mkenigs** [comment]
Tweaked the description to reflect the new name

**Pull request merged**
