### PR TITLE
feat: pass specialized context to flox envs

### PR DESCRIPTION
**Pull request by ysndr**
This is the follow up on the merged capacitor changes, allowing you to pass a system specialized context to the modules.
This is generally more consistent with how we use to call functions elsewhere when we have access to `system`

### CODE REVIEW

**Review by mkenigs — CHANGES_REQUESTED** [review]
We need to remove system as an argument and make sure it isn't used:
```
     error: anonymous function at /nix/store/wmgb9spmllwmnir0bvd9vs9yf8nx6spb-source/lib//mkFloxEnv.nix:5:4 called without required argument 'system'
   
            at /nix/store/wmgb9spmllwmnir0bvd9vs9yf8nx6spb-source/plugins/floxEnvs.nix:34:15:
   
                33|       # context.auto.callPackageWith injectedArgs floxNixPath {};
                34|       value = self.lib.mkFloxEnv {
                  |               ^
                35|         inherit namespace;
```

**Review by tomberek — APPROVED** [review]

**Comment by mkenigs** [comment]
> We need to remove system as an argument and make sure it isn't used:
> 
> ```
>      error: anonymous function at /nix/store/wmgb9spmllwmnir0bvd9vs9yf8nx6spb-source/lib//mkFloxEnv.nix:5:4 called without required argument 'system'
>    
>             at /nix/store/wmgb9spmllwmnir0bvd9vs9yf8nx6spb-source/plugins/floxEnvs.nix:34:15:
>    
>                 33|       # context.auto.callPackageWith injectedArgs floxNixPath {};
>                 34|       value = self.lib.mkFloxEnv {
>                   |               ^
>                 35|         inherit namespace;
> ```

@ysndr did you ever fix that?

**Comment by ysndr** [comment]
Ah no i don't think so, but ive wondered why we still used the non specialized context

**Comment by ysndr** [comment]
Though that error is referring to the function signature before the PR...

**Comment by limeytexan** [comment]
@ysndr ping ... can we get this updated and merged? Thx

**Comment by ysndr** [comment]
@mkenigs I cant reproduce this?
So far for me it seems to work on the envs that i tested it with.

**Comment by ysndr** [comment]
Since this OPR started we added root flox.nix
Added system specialization for those too now

**Pull request merged**
