### PR TITLE
treewide: use withRev to set revisioned version in templates

### PR DESCRIPTION
**Pull request by limeytexan**
The `withRev` function will append a "-rXXX" string to the version string to provide automatic tracking of version increments in package versions. Adding this to all templates by default.

### CODE REVIEW

**Comment by tomberek** [comment]
This API will only work when the source is in the same repo and is fetched via “git+”. So while it might be fine for individual projects that coexist with their code, it won’t work for anyone’s floxpkgs or when there is an external source. 

https://github.com/flox/decapacitor/blob/db4640ca0c0907b58018b17e10640b61b0ae1bbd/lib/capacitate/capacitate.nix#L103

The “ flakeArgs.self.revCount” only refers to the entry-point capacitated flake. So that is the only time this will be correct.

**Comment by tomberek** [comment]
Updating the function to be
```
getRev :: source -> string
```
to be used like:
```
version = "0.0.0-${getRev self}";
```
but i'm going to refrain from merging this until the lib interface is updated with overlay-trees. This should reduce the need for the `getRev ? inputs.floxpkgs.lib.getEnv` portion.

**Review by mkenigs — APPROVED** [review]

**Comment by tomberek** [comment]
Merged gitRev on its own, leaving template updates until the lib is exposed in a better way

**Comment by tomberek** [comment]
@ysndr do we have lib merging available that would make the templates simpler?

**Comment by limeytexan** [comment]
@ysndr @tomberek is this still blocked? This was supposed to be a simple treewide refactor; if we can't come up with the perfect solution now can we commit an interim improvement so that people using our templates can get the benefit of automatic revision tracking?

**Comment by limeytexan** [comment]
ping

**Comment by ysndr** [comment]
the current solution reads:
```
version = "0.0.0-${inputs.flox-floxpkgs.lib.getRev self}";
```

we can "hide" that somewhat in the "imports" section a cleaner(?) solution


```nix
{
  inputs,
  self,
  getRev ? inputs.flox-floxpkgs.lib.getRev,
  mkDerivation,
}:
mkDerivation {
	version = "0.0.0-r${getRev self}
}
```

**Comment by tomberek** [comment]
The library composition (https://github.com/flox/capacitor-private/pull/98#pullrequestreview-1233149347) will make this simpler.

**Pull request merged**
