### PR TITLE
feat: adding buildGradle template

### PR DESCRIPTION
**Pull request by samrose**

### CODE REVIEW

**Comment by samrose** [comment]
@jurraca this is the builder for gradle projects. The docs are forthcoming today in a different PR to floxdocs

**Comment by samrose** [comment]
accompanying docs https://github.com/flox/floxdocs/pull/227

**Comment by samrose** [comment]
I am working out 2 small issues on this, and it will be ready for review

**Comment by jurraca** [comment]
The docs are good, how do you feel about this template?

**Comment by samrose** [comment]
The template is made from a working example. So it should work and be worth including.

**Comment by limeytexan** [comment]
@jurraca I'm adding you to the assignee list to get this pushed over the line.

**Review by jurraca — APPROVED** [review]

**Pull request merged**
