### PR TITLE
feat:mkYarnPackage template

### PR DESCRIPTION
**Pull request by samrose**

### CODE REVIEW

**Comment by limeytexan** [comment]
We know from other languages that there can be multiple builders over time, often for the very same underlying ecosystem (e.g. buildRustPackage vs naersk.buildRustPackage). In that respect the path `templates/javascript-yarn/flake.nix` may not be a good choice. A better choice might be the name of the builder itself, because that exists in the Nix namespace and is guaranteed to be unique.

Another question - do we want to inject a directory level within templates for builders specifically? What other kinds of templates might we want to use, or are builders the only use for flake templates?

These are also questions that can answered later with a treewide refactoring so there's no need for this to block progress now, but thought I'd put it out there before we get too far down this path.

Thanks for building out the library of templates for `flox init`!!!  :-)

**Comment by mkenigs** [comment]
> A better choice might be the name of the builder itself, because that exists in the Nix namespace and is guaranteed to be unique.

If we do that, I think currently the folder name will be displayed in the `flox init` menu. Not sure if that's good or bad, just making a note
> 
> Another question - do we want to inject a directory level within templates for builders specifically? What other kinds of templates might we want to use, or are builders the only use for flake templates?

I think that could be nice, but right now capacitor doesn't support that

**Review by mkenigs — APPROVED** [review]

**Comment by limeytexan** [comment]
> If we do that, I think currently the folder name will be displayed in the flox init menu.

Currently, sure - but the flox cli sits in a position where it can massage the data returned by nix and turn that into a hierarchical menu driven experience. As long as we adhere to a convention we can make it look right to the user. 

Overall theme as with so many things is to think outside the Nix box.

**Comment by mkenigs** [comment]
> Currently, sure - but the flox cli sits in a position where it can massage the data returned by nix and turn that into a hierarchical menu driven experience. As long as we adhere to a convention we can make it look right to the user.

Agreed, just flagging as a work item!

**Pull request merged**
