### PR TITLE
proposed new packageset template

### PR DESCRIPTION
**Pull request by samrose**
This is a template to demonstrate (and test) the capability of floxpkgs and capacitor to automatically add attributes about packages added to a `/pkgs` directory in a package set

### CODE REVIEW

**Comment by limeytexan** [comment]
What is a packageset? Would our customers need to create one?

We expect for flox/floxpkgs to be pulled into every company's root flake, so the bar for adding something to the templates directory should be super high. If we're just needing this for a test then perhaps we should create a new floxpkgs repository for testing (it can be like its own company) and then add this template to that instead?

Also, up until now our use of templates has been solely in the context of "floxifying" source repositories. At present that is only for the purpose of creating developer environments but in future I'm confident we'll also be using it for creating Nix expressions for builds for use in conjunction with floxpkgs repositories. I think we should reserve the use of templates for use with source repositories, and/or if we do use them for other things we should namespace them accordingly so that the flox CLI can avoid including them in the menu presented to users.

**Comment by limeytexan** [comment]
@samrose this needs to come out. As mentioned above the public-facing floxpkgs repo should be for customers, not our internal use.

It is polluting the output of `flox init`:
```
brantley@Michaels-MBP tmp.WGwnSyKk1X % flox init

1) default: Template using specific versions
2) packageset: no description provided in /nix/store/cqr37qk34ndklpb7scwka8hi36mlzrcj-source/templates/packageset/flake.nix
3) python-black: Python Black example template
4) python-black-devshell: Python Black example template using devshell
5) python2: Python 2 template
6) python3: Python 3 template
Choose template by number: 
```
Thanks!

**Comment by samrose** [comment]
> @samrose this needs to come out. As mentioned above the public-facing floxpkgs repo should be for customers, not our internal use.
> 
> It is polluting the output of `flox init`:
> 
> ```
> brantley@Michaels-MBP tmp.WGwnSyKk1X % flox init
> 
> 1) default: Template using specific versions
> 2) packageset: no description provided in /nix/store/cqr37qk34ndklpb7scwka8hi36mlzrcj-source/templates/packageset/flake.nix
> 3) python-black: Python Black example template
> 4) python-black-devshell: Python Black example template using devshell
> 5) python2: Python 2 template
> 6) python3: Python 3 template
> Choose template by number: 
> ```
> 
> Thanks!

@limeytexan yes I reversed the commit when you alerted me to my accidental merging of it. It is removed now.

**Comment by limeytexan** [comment]
Thanks!

**Pull request merged**
