### PR TITLE
feat: floxEnv: support flakes, store paths, and nested attributes

### PR DESCRIPTION
**Pull request by mkenigs**
The new format supports specifying packages in the form:
packages = {
  nixpkgs-flox.hello = {};
  "github.com/nixos/nix".python3Packages.requests = {};
  "/nix/store/XXX-pkg-0.0.0" = {};
}

Flakes are fetched every time a floxEnv is built (until readPackage is
integrated), and storePaths are assumed to be present in the store

### CODE REVIEW

**Comment by mkenigs** [comment]
Still need to test against flox-internal integration tests

**Comment by mkenigs** [comment]
Latest changes produce the following catalog and manifest.

@tomberek I added `publish_element` rather than `original_element` because I want to preserve all the original information for eval and build (oh actually maybe we don't need build? I can drop that)

Things of note:
There is a single storePath for the publish of a publish of a multi-output derivation, but it's the wrapped store path created by buildenv that contains both outputs
url is indirect but includes rev: `flake:nixpkgs-flox/42aedd63d955f60c0c3065a909a4edc14c769b8b` As we discussed @tomberek there are some failure cases if flake registry entries don't contain branch name for git repos

<details>
<summary>flox.nix</summary>

```
{...}: {
  packages = {
    "github:nixos/nixpkgs".python3Packages.requests = {};
    nixpkgs-flox.curl = {};
  };
}
```
</details>

<details>
<summary>manifest.json</summary>

```
{
  "elements": [
    {
      "active": true,
      "attrPath": "evalCatalog.aarch64-darwin.stable.curl",
      "outputs": null,
      "storePaths": [
        "/nix/store/42bf0hifng26q01j05h69b48sdy707bj-curl-7.86.0"
      ],
      "url": "flake:nixpkgs-flox/42aedd63d955f60c0c3065a909a4edc14c769b8b"
    },
    {
      "active": true,
      "attrPath": "legacyPackages.aarch64-darwin.python3Packages.requests",
      "outputs": null,
      "storePaths": [
        "/nix/store/qjqk1bnlmgzwzkwn4kk0kv03i891zasx-python3.10-requests-2.28.1"
      ],
      "url": "github:nixos/nixpkgs/b10a520017ac319c1e57b07742efd2bcc918d160"
    }
  ],
  "version": 2
}
```
</details>


<details>
<summary>catalog.json</summary>

```
{
  "github:nixos/nixpkgs": {
    "aarch64-darwin": {
      "python3Packages": {
        "requests": {
          "build": {
            "hasBin": false,
            "hasMan": false
          },
          "element": {
            "active": true,
            "attrPath": [
              "legacyPackages",
              "aarch64-darwin",
              "python3Packages",
              "requests"
            ],
            "originalUrl": "github:nixos/nixpkgs",
            "storePaths": [
              "/nix/store/qjqk1bnlmgzwzkwn4kk0kv03i891zasx-python3.10-requests-2.28.1"
            ],
            "url": "github:nixos/nixpkgs/b10a520017ac319c1e57b07742efd2bcc918d160"
          },
          "eval": {
            "attrPath": [
              "legacyPackages",
              "aarch64-darwin",
              "python3Packages",
              "requests"
            ],
            "drvPath": "/nix/store/bk3575hksr7piq4h5171cywy520p10aq-python3.10-requests-2.28.1.drv",
            "meta": {
              "available": true,
              "broken": false,
              "description": "HTTP library for Python",
              "homepage": "http://docs.python-requests.org/",
              "insecure": false,
              "isBuildPythonPackage": [
                "aarch64-linux",
                "armv5tel-linux",
                "armv6l-linux",
                "armv7a-linux",
                "armv7l-linux",
                "i686-linux",
                "m68k-linux",
                "microblaze-linux",
                "microblazeel-linux",
                "mipsel-linux",
                "mips64el-linux",
                "powerpc64-linux",
                "powerpc64le-linux",
                "riscv32-linux",
                "riscv64-linux",
                "s390-linux",
                "s390x-linux",
                "x86_64-linux",
                "x86_64-darwin",
                "i686-darwin",
                "aarch64-darwin",
                "armv7a-darwin"
              ],
              "license": {
                "deprecated": false,
                "free": true,
                "fullName": "Apache License 2.0",
                "redistributable": true,
                "shortName": "asl20",
                "spdxId": "Apache-2.0",
                "url": "https://spdx.org/licenses/Apache-2.0.html"
              },
              "maintainers": [
                {
                  "email": "mail@fabian-affolter.ch",
                  "github": "fabaff",
                  "githubId": 116184,
                  "keys": [
                    {
                      "fingerprint": "2F6C 930F D3C4 7E38 6AFA  4EB4 E23C D2DD 36A4 397F"
                    }
                  ],
                  "matrix": "@fabaff:matrix.org",
                  "name": "Fabian Affolter"
                }
              ],
              "name": "python3.10-requests-2.28.1",
              "outputsToInstall": [
                "out"
              ],
              "platforms": [
                "aarch64-linux",
                "armv5tel-linux",
                "armv6l-linux",
                "armv7a-linux",
                "armv7l-linux",
                "i686-linux",
                "m68k-linux",
                "microblaze-linux",
                "microblazeel-linux",
                "mipsel-linux",
                "mips64el-linux",
                "powerpc64-linux",
                "powerpc64le-linux",
                "riscv32-linux",
                "riscv64-linux",
                "s390-linux",
                "s390x-linux",
                "x86_64-linux",
                "x86_64-darwin",
                "i686-darwin",
                "aarch64-darwin",
                "armv7a-darwin"
              ],
              "position": "/nix/store/azscwjan2b8vkv2dqrig353w4npf34sh-source/pkgs/development/python-modules/requests/default.nix:85",
              "unfree": false,
              "unsupported": false
            },
            "name": "python3.10-requests-2.28.1",
            "namespace": [],
            "outputs": {
              "dist": "/nix/store/8c0ckfvycdy9l1wv3kplwy9mpvqdcwn2-python3.10-requests-2.28.1-dist",
              "out": "/nix/store/qjqk1bnlmgzwzkwn4kk0kv03i891zasx-python3.10-requests-2.28.1"
            },
            "pname": "python3.10-requests",
            "system": "aarch64-darwin",
            "version": "2.28.1"
          }
        }
      }
    }
  },
  "nixpkgs-flox": {
    "aarch64-darwin": {
      "stable": {
        "curl": {
          "latest": {
            "element": {
              "attrPath": [
                "legacyPackages",
                "aarch64-darwin",
                "curl"
              ],
              "originalUrl": "flake:nixpkgs",
              "outputs": null,
              "storePaths": [
                "/nix/store/makx8xb122d0ildfqbc00hgj8393wm1n-curl-7.86.0-bin",
                "/nix/store/rkvia85dqq40rj3rv385qg9k445k5wjy-curl-7.86.0-man"
              ],
              "url": "github:flox/nixpkgs/2788904d26dda6cfa1921c5abb7a2466ffe3cb8c"
            },
            "eval": {
              "meta": {
                "description": "A command line tool for transferring files with URL syntax",
                "outputsToInstall": [
                  "bin",
                  "man"
                ],
                "position": "/nix/store/nv78zywp4j59l8lkmzbw881i5r3swwda-source/pkgs/tools/networking/curl/default.nix:185",
                "unfree": false
              },
              "name": "curl-7.86.0",
              "outputs": {
                "bin": "/nix/store/makx8xb122d0ildfqbc00hgj8393wm1n-curl-7.86.0-bin",
                "dev": "/nix/store/svnrmka6ai6h1gg7llsql1asmfdg4gw2-curl-7.86.0-dev",
                "devdoc": "/nix/store/fa3afvj2xngkxik6jh44gmrwj8lk2vpr-curl-7.86.0-devdoc",
                "man": "/nix/store/rkvia85dqq40rj3rv385qg9k445k5wjy-curl-7.86.0-man",
                "out": "/nix/store/w4g2mhzv8cniz96d5mna8l8yrxxizf9y-curl-7.86.0"
              },
              "pname": "curl",
              "system": "aarch64-darwin",
              "version": "7.86.0"
            },
            "publish_element": {
              "active": true,
              "attrPath": [
                "evalCatalog",
                "aarch64-darwin",
                "stable",
                "curl"
              ],
              "originalUrl": "flake:nixpkgs-flox",
              "storePaths": [
                "/nix/store/42bf0hifng26q01j05h69b48sdy707bj-curl-7.86.0"
              ],
              "url": "flake:nixpkgs-flox/42aedd63d955f60c0c3065a909a4edc14c769b8b"
            }
          }
        }
      }
    }
  }
}
```
</details>

**Review by tomberek — CHANGES_REQUESTED** [review]
Keep the env.bash, or at least fold the functionality into activate + it’s various shell helpers.

**Comment by mkenigs** [comment]
> Keep the env.bash, or at least fold the functionality into activate + it’s various shell helpers.

Twas debugging, but I dropped that commit

**Review by tomberek — APPROVED** [review]

**Pull request merged**
