### PR TITLE
feat: templates/java adding java template

### PR DESCRIPTION
**Pull request by samrose**

### CODE REVIEW

**Comment by samrose** [comment]
per @limeytexan closing this PR as it is already covered under the `mkDerivation` template

**Comment by mkenigs** [comment]
Reopening for similar reasons as https://github.com/flox/floxpkgs/pull/45#issuecomment-1245980993

**Review by limeytexan — APPROVED** [review]
Looks fine, but circle back with @ysndr as he was starting an effort to remove flake.nix from templates going forward.

**Comment by mkenigs** [comment]
Does this need to observe the new naming scheme using the builder? Although I've lost track of what that actually is 🤦

**Comment by ysndr** [comment]
The new structure for these templates is documented in: https://github.com/flox/decapacitor/pull/79

```
./templates
└── javaPackage
   ├── template.nix    # = { description = "Java PAckages Scaffold"; }
   └── files
      └── pkgs
         └── default.nix
```

**Comment by samrose** [comment]
> The new structure for these templates is documented in: [flox/decapacitor#79](https://github.com/flox/decapacitor/pull/79)
> 
> ```
> ./templates
> └── javaPackage
>    ├── template.nix    # = { description = "Java PAckages Scaffold"; }
>    └── files
>       └── pkgs
>          └── default.nix
> ```

done

**Pull request merged**
